[phases.setup]
nixPkgs = ['python39', 'pip']

[phases.install]
cmds = ['pip install -r requirements_replit.txt']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'python iqoption_unofficial_server.py'
