[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python iqoption_unofficial_server.py"
healthcheckPath = "/api/status"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PORT = "5000"
